version: '3'

services:
  pgconsul1:
    image: consul:1.12.3
    hostname: "${HOSTNAME}"
    environment:
      TZ: Europe/Istanbul
    networks:
      - pgbacknet
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/data
    restart: unless-stopped
    command: agent -server -advertise $CONSUL_PUBLIC_IP -bootstrap-expect 1 -client 0.0.0.0 -retry-join $CONSUL_PUBLIC_IP # -retry-join MY_2_HOST_IP -retry-join MY_3_HOST_IP

volumes:
  consul-data:

# network: pgbacknet
networks:
  pgbacknet:
    name: pgbacknet
    driver: bridge